# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputToken.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QLineEdit


##############################################
# Window in which user input token information
##############################################


class Ui_Dialog(object):
    di = ''
    tokenhandler = ''
    
    def setupUi(self, Dialog, Tokenhandler):
        self.tokenhandler = Tokenhandler
        self.di = Dialog
        Dialog.resize(541, 135)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(400, 10, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 80, 281, 20))
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setEchoMode(QLineEdit.Password)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 50, 281, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 20, 281, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")


        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.input_token)
        self.buttonBox.rejected.connect(self.cancel_input)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "请登录！"))
        self.label.setText(_translate("Dialog", "邮箱地址："))
        self.label_2.setText(_translate("Dialog", "邮箱域用户名:"))
        self.label_3.setText(_translate("Dialog", "密码:"))

    def input_token(self):
        self.tokenhandler.current_mail_address = self.lineEdit_3.text()
        self.tokenhandler.current_username = self.lineEdit_2.text()
        self.tokenhandler.current_password = self.lineEdit.text()
        self.di.close()

    def cancel_input(self):
        sys.exit()



